---
- hosts: all
  become: true
  tasks:
   - name: Install package
     yum: 
        name: httpd 
        state: present

   - name: creating index file
     copy:
        content: "Hello world"
        dest: /var/www/html/index.html
        force: no
        group: apache
        owner: apache
        mode: 0555
      
   - service: 
        name: httpd
        state: "{{ apache_state }}"
